defaults:
  - _self_
  - model: dncnn_small
  - data: test_dummy_mnist
pl_trainer:
  max_epochs: 100
  gpus: 1
  check_val_every_n_epoch: 1
seed: 1234
processing_dir: './processing/train'
hydra:
  run:
    dir: ${processing_dir}
